export interface IGameData {
    id: number,
    href: string,
    preview: string,
    title: string,
    description: string,
    lastActivity: string,
    currentTickets: number,
    totalTickets: number,
    record: string,
    recordBackground?: string,
    recordBorder?: string,
    svgColor: string,
    textColor: string,
    width: string,
    height: string,
    recordPreview: string,
    backgroundColor: string,
    howPlay: string[]
}