export interface IItemCard {
    id: number,
    model: string,
    itemType?: string,
    type: string,
    typeName?: string,
    count: number,
    img: string,
    title: string,
    rarity: string,
    hint?: string,
    price: number,
    rarityBackground: string,
    topShadow?: string,
    rarityButton?: string,
    rarityShadow?: string,
    rarityBorder?: string,
    rarityCategoryShadow?: string,
    rarityCategoryBackground?: string,
    popupRarityBorder?: string
}